### ISSUE TITLE
player wird nicht angezeigt nach scan

### ISSUE THREAD

**Issue by TheSpirit** [Liver64/LoxBerry-Sonos#1]
wenn ich scan zonen anklicke wird nach einiger zeit eine zeile angezeigt, in der die felder 
Raum und Modell aber leer sind

**Comment by Liver64** [comment]
Welche LoxBerry Version? Das Plugin benötigt 0.2.3. Welchen Router nutzt du? Hast du die neueste Version von heute installiert?

**Comment by TheSpirit** [comment]
loxberry ist version 0.2.3
router ist eine fritzbox 7390
version ist 0.8

**Comment by Liver64** [comment]
Die Versionierung im Beta Test Status ist nicht aktuell. Bitte lade dir ein neues Paket (8.1) runter. 
Versuche mal die Firewall auszuschalten! Nutzt du IPv4 oder IPv6 IP-Adressen? Ist Sonos im WLAN oder LAN?

**Comment by Liver64** [comment]
evtl. hast du ein Virenscanner oder Firewall Problem so dass Multicast für UPnP nicht funktioniert.
Vielleicht hilft dir das hier!
https://sonos.custhelp.com/app/answers/detail/a_id/610

**Comment by TheSpirit** [comment]
habe gerade nochmal runtergeladen, aber es wird noch immer version 0.8 angezeigt.
was mache ich da falsch?
firewall ausschalten? wo? hier ist alles mac, kein windows.
Adresse ist IPv4.
Sonos ist per WLAN erst mit Repeater und dann per WLAN mit Fritzbox verbunden.
Meinst du der Virenscanner auf dem Rechner macht probleme?

**Comment by Liver64** [comment]
Die Version ist derzeit nur in der sonos2.php zu finden, müsste 0.8.1 sein.
Da ich aktuell keinen Mac habe kann ich dir leider nicht helfen, aber soweit ich weiß hat auch der eine Firewall und ggf. einen Virenscanner. Hast du google mal gefragt? z.B. "enable Multicast UPnP OS X"
folgendes habe ich gefunden:
http://www.thomasqvarnstrom.com/2015/06/multicasting-routing-on-mac.html

**Comment by TheSpirit** [comment]
hab jetzt noch einen alten windows laptop angemacht.
leider das gleiche problem.
sieht dort genauso aus.
![image](https://cloud.githubusercontent.com/assets/6056918/21521117/31ac8d58-ccfa-11e6-9c4a-a07309e1a08c.png)

**Comment by Liver64** [comment]
Dann muss irgendwas mit deiner Fritzbox nicht korrekt sein. Und du hast sicher in deinem Netzwerk keinen LAN switch? Was zeigt denn deine Topology an?
http://IP-ADRESSE EINER ZONE:1400/status/topology

**Comment by Liver64** [comment]
Da kann ich dir von hier leider wenig helfen :-( Die anderen Tester hatten da keine Probleme, von daher muss es an deinem Netzwerk liegen. Multicast ist eigentlich ein gängiger Standard um bestimmte Netzwerkkomponenten per Bulk zu erreichen.

**Comment by Liver64** [comment]
Was sagt denn dein error log? 
\loxberry\log\system\apache2\error.log

**Comment by TheSpirit** [comment]
Ein Switch ist vorhanden, aber die Play:1 hängt ja am WLAN; 
Der LoxBerry hängt am switch.
Ich teste den LoxBerry mal direkt an der Fritzbox und gebe Bescheid

**Comment by TheSpirit** [comment]
jetzt jängt der loxberry direkt an der fritzbox mit dem gleichen ergebnis.
hier der error.log

[error.txt](https://github.com/Liver64/LoxBerry-Sonos/files/675691/error.txt)

jetzt noch die info aus topology:

![image](https://cloud.githubusercontent.com/assets/6056918/21524599/ad0c536c-cd17-11e6-8afe-b8772395986e.png)

**Comment by Liver64** [comment]
ok, fehler gefunden, jetzt müssen wir ihn nur noch beseitigen. Du hast, wenn ich es richtig rauslese, 2 Player. Einen mit IP 192.168.178.44 und 192.168.178.25 Richtig? Welche Sonos Modelle sind das?
Mache bitte mal folgendes: copy/paste den link in deinen Browser:
http://192.168.178.44:1400/xml/device_description.xml
http://192.168.178.25:1400/xml/device_description.xml
Dann müsstest du je Zone ziemlich viele Details sehen. Das Skript versucht diese Dateien zu öffnen, findet Sie aber nicht, von daher bekommst du sie nicht in die Konfig.

**Comment by TheSpirit** [comment]
ich habe nur eine Play:1

**Comment by Liver64** [comment]
mit welcher IP?

**Comment by TheSpirit** [comment]
nur mit
http://192.168.178.44:1400/xml/device_description.xml
bekomm ich viele infos

**Comment by Liver64** [comment]
Was für ein Kürzel steht denn unter device modelNumber?
![image](https://cloud.githubusercontent.com/assets/19775860/21524720/a15830a8-cd18-11e6-9466-1968314c98e5.png)

**Comment by TheSpirit** [comment]
![image](https://cloud.githubusercontent.com/assets/6056918/21524737/c394acbe-cd18-11e6-90c9-bd5e512fb6cc.png)

**Comment by Liver64** [comment]
OK, Fehler gefunden. Das Model S12 habe ich nicht in der Liste der zulässigen Player. Eigentlich ist eine PLAY:1 das Modell S1. Wie auch immer, habe die S12 hinzugefügt. Lade dir bitte NUR die Datei network.php neu herunter und probiere dann noch einmal.
Daumen drücken

**Comment by TheSpirit** [comment]
so. gerade getestet.
leider wie oben. 
https://cloud.githubusercontent.com/assets/6056918/21521117/31ac8d58-ccfa-11e6-9c4a-a07309e1a08c.png
er findet zwar was, aber die felder sind leer.
hier der neue log
[error.txt](https://github.com/Liver64/LoxBerry-Sonos/files/675798/error.txt)

**Comment by Liver64** [comment]
Hast du die Box evtl. per DHCP connected?
Zieh sie doch bitte für 5 Minuten vom Strom und dann wieder dran und gebe ihr eine fixe IP in der Fritzbox

**Comment by TheSpirit** [comment]
ich test das mal;
sonos box in der fritzbox auf "immer die gleiche ip adresse zuweisen" gestellt.
leider immer noch das gleiche
hier der log dazu
[error.txt](https://github.com/Liver64/LoxBerry-Sonos/files/675912/error.txt)

hab jetzt auch noch herausgefunden was mein .25 device ist:
das ist meine Philips Hue Bridge.
Vielleicht stört die ja auch noch, da diese im errorlog auch immer auftaucht

edit 1:
weitere tests haben gezeigt, das ich vom loxberry aus meine Play:1 garnicht pingen kann.
heise.de kann ich aber zum beispiel anpingen.
vielleicht ist dort ja noch ein wurm drin.
leider fehlt mir ne idee warum das so ist

edit 2:
mit midoria als webbrowser auf dem pi geht zwar das hier
http://192.168.178.44:1400/status/topology
jedoch klappt das hier nicht:
http://192.168.178.44:1400/xml/device_description.xml

scheint so, als könne der pi kein xml lesen, oder?

**Comment by TheSpirit** [comment]
so, hab das problem jetzt denk ich lokalisieren können.
wenn ich die sonos box mittels lan-kabel anschließe kann ich die box ohne packet loss pingen und das plugin läuft.
hänge ich die sonos box aber ins wlan, dann kann ich mittels scan die sonos box nicht mehr finden und ich habe massive packet losses

>loxberry@loxberry:~ $ ping 192.168.178.44
PING 192.168.178.44 (192.168.178.44) 56(84) bytes of data.
64 bytes from 192.168.178.44: icmp_seq=47 ttl=64 time=3.05 ms
64 bytes from 192.168.178.44: icmp_seq=81 ttl=64 time=3.68 ms
64 bytes from 192.168.178.44: icmp_seq=112 ttl=64 time=5.11 ms
64 bytes from 192.168.178.44: icmp_seq=236 ttl=64 time=3.21 ms
64 bytes from 192.168.178.44: icmp_seq=267 ttl=64 time=3.26 ms
64 bytes from 192.168.178.44: icmp_seq=300 ttl=64 time=4.40 ms
64 bytes from 192.168.178.44: icmp_seq=331 ttl=64 time=3.93 ms
64 bytes from 192.168.178.44: icmp_seq=362 ttl=64 time=3.67 ms
--- 192.168.178.44 ping statistics ---
371 packets transmitted, 8 received, 97% packet loss, time 370092ms
rtt min/avg/max/mdev = 3.057/3.792/5.116/0.649 ms

jetzt ist halt nur die frage, warum ich mittels wlan solch massiven probleme habe.
die naviagation in der sonos app ist hingegen egal ob per lan, oder wlan immer ohne jegliche verzögerung.

**Comment by Liver64** [comment]
Ist in der Tat etwas seltsam... Ich kann mich vage daran erinnern das ich ähnliches auch mal vor sehr langer Zeit hatte. Ich habe dann den Sonos WLAN Kanal geändert. Um optimalen Empfang bei mehreren WLAN Netzen zu haben soll man glaube ich 5 Kanäle dazwischen haben. Mein Standard WLAN läuft auf Kanal 11 und SonosNet auf Kanal 6. seitdem hatte ich mir wieder Probleme. Alternativ gibt Google auch einiges her bei "packet loss sonos".
