### ISSUE TITLE
Jingle MP3

### ISSUE THREAD

**Issue by KultGrazer** [Liver64/LoxBerry-Sonos#14]
Wenn kein "Dateiname für Jingle MP3" gewählt ist, kommt ein Syntax-Error bei "playgong=yes"

Dropdown mit allen MP3's des Ordners und vordefinierte File würde den Fehler aushebeln.

BTW: Geiles Plugin ;-)

**Comment by Liver64** [comment]
Danke für den Hinweis, hatte ich auch schon drüber nachgedacht, ist aber nicht Prio 1. Habe jetzt erst einmal ein error handling eingebaut, kommt dann mit dem nächsten Release

**Comment by Liver64** [comment]
habe es jetzt als Dropdown zur Auswahl + die Möglichkeit je TTS ein anderes jingle zu spielen.
