### ISSUE TITLE
Problem beim Scannen der Player

### ISSUE THREAD

**Issue by marco0815** [Liver64/LoxBerry-Sonos#15]
Guten Abend,
bekomme das Sonos Plugin leider nicht zum Laufen.

**Situation 1 - Raspi3 mit Loxberry 1.2.1.5 & Sonos Plugin 3.4.4**
Sonos Plugin lässt sich öffnen jedoch bekomme ich beim Scannen der Zonen die Meldung "The temporary scan file 'tmp_player.json' could not be opened!".

Im Log steht folgendes:

`OK: 19:52:43 Sonos Plugin has been successfully loaded.
19:53:14 Read main settings from sonos.ini for language: de
19:53:14 The Sonos config file has been loaded
19:53:14 The Sonos player file has been loaded
19:53:14 Loxone Miniserver(s) has been detected
19:53:15 0 Radio Stations has been loaded.
19:53:15 0 Sonos players has been loaded.
19:53:15 Scan request for Sonos Zones has been executed.
19:53:15 SSDP-Service is up and running
19:53:17 Read main settings from sonos.ini for language: de
19:53:17 The Sonos config file has been loaded
19:53:17 The Sonos player file has been loaded
19:53:17 Loxone Miniserver(s) has been detected
19:53:18 0 Radio Stations has been loaded.
19:53:18 0 Sonos players has been loaded.
[18-Jun-2018 19:53:18 Europe/Berlin] INFO: PHP-> Initial network scan (MULTICAST) for supported Sonos devices in your network will be executed.
[18-Jun-2018 19:53:19 Europe/Berlin] PHP Fatal error: Uncaught RuntimeException: No devices found on the current network in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/vendor/duncan3dc/sonos/src/Network.php:270
Stack trace:
#0 /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/network.php(30): duncan3dc\Sonos\Network->getSpeakers()
#1 {main}
thrown in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/vendor/duncan3dc/sonos/src/Network.php on line 270
ERROR: 19:53:19 File: tmp_player.json could not be opened! Please execute Scan Zones again.
19:53:19 List of available Miniserver(s) has been successful loaded
19:53:19 List of MP3 files has been successful loaded
OK: 19:53:19 Sonos Plugin has been successfully loaded.
19:53:21 Read main settings from sonos.ini for language: de
19:53:21 The Sonos config file has been loaded
19:53:21 The Sonos player file has been loaded
19:53:21 Loxone Miniserver(s) has been detected
19:53:21 0 Radio Stations has been loaded.
19:53:21 0 Sonos players has been loaded.
19:53:21 Read main settings from sonos.ini for language: de
19:53:21 The Sonos config file has been loaded
19:53:21 The Sonos player file has been loaded
19:53:21 Loxone Miniserver(s) has been detected
19:53:21 0 Radio Stations has been loaded.
19:53:21 0 Sonos players has been loaded.
[18-Jun-2018 19:53:21 Europe/Berlin] INFO: PHP-> Initial network scan (MULTICAST) for supported Sonos devices in your network will be executed.
[18-Jun-2018 19:53:21 Europe/Berlin] INFO: PHP-> Initial network scan (MULTICAST) for supported Sonos devices in your network will be executed.
[18-Jun-2018 19:53:22 Europe/Berlin] PHP Fatal error: Uncaught RuntimeException: No devices found on the current network in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/vendor/duncan3dc/sonos/src/Network.php:270
Stack trace:
#0 /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/network.php(30): duncan3dc\Sonos\Network->getSpeakers()
#1 {main}
thrown in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/vendor/duncan3dc/sonos/src/Network.php on line 270
[18-Jun-2018 19:53:22 Europe/Berlin] PHP Fatal error: Uncaught RuntimeException: No devices found on the current network in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/vendor/duncan3dc/sonos/src/Network.php:270
Stack trace:
#0 /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/network.php(30): duncan3dc\Sonos\Network->getSpeakers()
#1 {main}
thrown in /opt/loxberry/webfrontend/html/plugins/sonos4lox/system/vendor/duncan3dc/sonos/src/Network.php on line 270
ERROR: 19:53:22 File: tmp_player.json could not be opened! Please execute Scan Zones again.
19:53:23 List of available Miniserver(s) has been successful loaded
19:53:23 List of MP3 files has been successful loaded
OK: 19:53:23 Sonos Plugin has been successfully loaded.
ERROR: 19:53:22 File: tmp_player.json could not be opened! Please execute Scan Zones again.
19:53:23 List of available Miniserver(s) has been successful loaded
19:53:23 List of MP3 files has been successful loaded
OK: 19:53:23 Sonos Plugin has been successfully loaded.`

**Situation 2 - Loxberry 1.0.3. & Sonos Plugin 3.4.4 (wurde getestet weil auf der Pluginübersicht der Status bei 1.0.3 mit "Stable" gekennzeichnet ist.**

Die Installation lief meines Erachtens ohne Fehlermeldungen durch.
Beim Öffnen des Plugins über die Weboberfläche bekomme ich folgende Meldung angezeigt:

`Can't locate LoxBerry/Storage.pm in @INC (you may need to install the LoxBerry::Storage module) (@INC contains: /opt/loxberry/libs/perllib /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/arm-linux-gnueabihf/perl5/5.24 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /opt/loxberry/webfrontend/htmlauth/plugins/sonos4lox/index.cgi line 25.
BEGIN failed--compilation aborted at /opt/loxberry/webfrontend/htmlauth/plugins/sonos4lox/index.cgi line 25.`

Bitte um Hilfe und bedanke mich im Voraus
LG

**Comment by Liver64** [comment]
please install Pre-release v3.4.7 and test

**Comment by marco0815** [comment]
It´s working! 
Thank you very much!!
