### ISSUE TITLE
PHP warning 'Undefined index'

### ISSUE THREAD

**Issue by christianTF** [Liver64/LoxBerry-Sonos#20]
![image](https://user-images.githubusercontent.com/14220265/58480396-90ecf980-815a-11e9-9228-410e2b23d48d.png)

Version 3.7.2

**Comment by Liver64** [comment]
Version 3.7.2 still not exist since 17/04/2019, problem fixed with v3.8.0

**Comment by christianTF** [comment]
Stimmt, ich hab vergessen, dass ich ja einmal manuell updaten muss wegen der Plugin-Update-Url. Deswegen dachte ich, ich wäre aktuell.... ;-)

**Comment by christianTF** [comment]
Version 3.8.2
kommt immer noch, aber weil ich kein Sonos hab, ist's vielleicht deswegen.
