### ISSUE TITLE
Function fgetss() is deprecated in PHP 7.3

### ISSUE THREAD

**Issue by Rello** [Liver64/LoxBerry-Sonos#21]
Hello,

7.3 has deprecated fgetss()
I this kown already? Any suggestion on fixing?

https://github.com/Liver64/LoxBerry-Sonos/blob/master/webfrontend/html/system/PHPSonos.php#L2812

thank you

**Comment by Liver64** [comment]
actually the LoxBerry (Debian Stretch) uses v7.1, so no issue at all.

**Comment by Rello** [comment]
https://github.com/Liver64/LoxBerry-Sonos/commit/3add38e212ffc612c37223ce5c24796f46e2c0b7

thanks for fixing
