### ISSUE TITLE
voluemup und volumedown funktionieren nicht mehr

### ISSUE THREAD

**Issue by scharrin2** [Liver64/LoxBerry-Sonos#22]
Seit dem Update auf die Version 3.9.0 funktionieren bei mir die Aktionen volumeup, volumedown und getvolume nicht mehr.

Die Aktionen volumeup und volumedown setzen die Lautstärke immer auf die Standard-Lautstärke (bei mir 10). Wenn ich die Lautstärke explizit auf einen festen Wert setze, funktioniert es.

Die Aktion getvolume liefert bei mir immer den Wert 0 zurück.

Nach einem Downgrade auf die Version 3.8.4 funktioniert wieder alles wie gewünscht.

**Comment by spangenberg** [comment]
Bei mir das selbe, der Fehler muss dann hier irgendwo sitzen: https://github.com/Liver64/LoxBerry-Sonos/commit/38d366664adefb8394f8b13ec21a6f2697ec933d

**Comment by Liver64** [comment]
kann mal bitte einer von euch 2 folgendes probieren (Nur mit Notepad++):
Die Datei webfrontend/html/plugins/sonos4lox/system/ PHPSonos.php öffnen und in Zeile 2812 bzw. 2813 gehen und folgendes ändern:
#$ret.= fgets($fp,128); 
$ret.= fgetss($fp,128);
Und anschließend speichern und testen
Danke

**Comment by scharrin2** [comment]
Hallo,
ich habe wieder die Version 3.9.0 installiert und die Zeile angepasst.
Jetzt geht es wieder.
Sowohl getvolume, volumeup und volumedown.

Viele Grüße,
Christian

**Comment by Liver64** [comment]
Danke, werde es nach dem Urlaub korrigieren

**Comment by scharrin2** [comment]
Hallo,
ich habe heute die Version 3.9.1 installiert. Leider ist der Fehler mit volumeup und volumedown noch vorhanden.
Soll ich die obige Datei nochmal editieren?

Viele Grüße,
Christian

**Comment by Liver64** [comment]
Nein, installiere bitte v3.9.2

**Comment by scharrin2** [comment]
Vielen Dank!

Jetzt funktioniert es wieder.
