### ISSUE TITLE
Fehler bei der Installtion

### ISSUE THREAD

**Issue by Clemens-XXX** [Liver64/LoxBerry-Sonos#27]
Die Installation des Plugin meldet an zwei Stellen:

```
Package libcurl3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
libcurl4

E: Package 'libcurl3' has no installation candidate
```
Und damit dann am Ende 
`APT install: (Some) Packages could not be installed.`

**Comment by Liver64** [comment]
bitte aktuellste Version laden

**Comment by Clemens-XXX** [comment]
das war heute mit Version 3.9.2 (laut Wiki die aktuellste)

**Comment by Clemens-XXX** [comment]
Ah, im Loxberry wird eine höhere Version angezeigt als im Wiki. Und trotz aktiviertem Autoupdate nicht installiert. jetzt manuell nachgeholt. Dann alles OK.

**Comment by Liver64** [comment]
fixed by User
