### ISSUE TITLE
Use second adapter to scan for sonos systems

### ISSUE THREAD

**Issue by HannesG79** [Liver64/LoxBerry-Sonos#32]
I have a loxberry with 2 nics to separate the sonos from the "control" network.
in ifconfig i have to interfaces
1) 192.168.1.0/24 with default gateway (default adapter of loxberry)
2) 192.168.2.0/24 no default gateway (this is the range of the sonos)
the plugin only scans the network 192.168.1.0/24 (multicasts)

is it possible to add a funktion to use the second adapter as well

**Comment by Liver64** [comment]
If it doesn‘t find any devices normally a broadcast scan will be executed

**Comment by Liver64** [comment]
in v3.9.8 you can amend IP-adresses
