### ISSUE TITLE
push_loxone.php causes 100% cpu utilization

### ISSUE THREAD

**Issue by janrudolph** [Liver64/Loxberry-Sonos#36]
Hi,

I observed a pretty strange behaviour. Since recently, the process push_loxone.php utilises 100% of 2 to 4 cpu cores of my loxberry. This heavy load results in a high temperature of the Raspberry (this is how i found the issue):

![image](https://user-images.githubusercontent.com/3596824/156637710-cf2db3d5-586c-4d6c-ad28-78515f480b52.png)

Plugin version: 4.1.0

Unfortunately, restarting the Loxberry is only helpful in the short term. After a couple of hours, the issue returns. 

I cannot assure that this issue only occurred after upgrading to 4.1.0. Before, I did not monitor my Loxberry, however, the Loxberry never had any temperature issues.
 

Further information:
- Upgrade to 4.1.0 at 28.02.2022 04:24, first temperature alarm which I noticed at 01.03.2022 04:41:08
- I use outgoing data transmission via UDP
- MQTT plugin is also installed, but not used for Sonos events

**Comment by Liver64** [comment]
should be fixed. Please test and provide feedback

**Comment by janrudolph** [comment]
seems fine, thanks :)
