### ISSUE TITLE
Please save your Config first!! error during UDP_Sonos.XML file creation

### ISSUE THREAD

**Issue by Superbenneken** [Liver64/Loxberry-Sonos#37]
Dear, 

I'm configuring TTS setting in loxberry for Sonos4lox. 
I'm unable to retrieve the UDP_Sonos.XML file due to error 'Please save your Config first!!'. 
This is done so I have no idea how to continue:
![afbeelding](https://user-images.githubusercontent.com/106996683/172223145-907a19ae-9211-4cdd-be0f-2ea066512efc.png)
 
![afbeelding](https://user-images.githubusercontent.com/106996683/172223316-0a16952c-4be5-456f-986f-69f715d0e9e3.png)

Can you guide me on how to solve this? Am I missing something or is there a bug? 

Br, 
Ben

**Comment by Liver64** [comment]
Did you entered UDP Port? And update to newest Version pls.

**Comment by Superbenneken** [comment]
The UDP port is filled in in the Sonos4Lox plugin. Do i need to fill it in somewhere else? 
Newest version of plugin is 4.1.5 right? That is the one installed.

**Comment by Liver64** [comment]
No, just in the Plugin in order to get XML generated. Actual Version is 5.1.4

**Comment by simcen** [comment]
I am running Sonos4Lox 5.1.8 on a brand new loxberry and running into the same issue. I have added the UDP port first, saved the config, and clicking the VI_UDP_Sonos.xml button throws the same error as mentioned above.

**Comment by Liver64** [comment]
is it nox fixed by using v5.3.0?
