### ISSUE TITLE
playradiofavorites

### ISSUE THREAD

**Issue by Chrone86** [Liver64/Loxberry-Sonos#38]
Hello

In my setup, i add and remove member with the action addmember/removemember:
/plugins/sonos4lox/index.php?zone=buero&action=addmember&member=dusche
/plugins/sonos4lox/index.php?zone=buero&action=removemember&member=dusche

This works well.

When i use the action=playradiofavorites on this group/zone, only the master "buero" changes the playlist and the other members builds their own zone with the "old" playlist:
/plugins/sonos4lox/index.php/?zone=buero&action=playradiofavorites

Regards

**Comment by Liver64** [comment]
Why do you do it in 2 steps? Just use:

/plugins/sonos4lox/index.php/?zone=buero&action=playradiofavorites&member=dusche

**Comment by Liver64** [comment]
No response, closed
