### ISSUE TITLE
Manuel reste

### ISSUE THREAD

**Issue by Pilaarbijter** [Liver64/Loxberry-Sonos#39]
Hello,

I use this plugin in order to play a specific mp3 file that is on my server everytime someone's ringing at my door.
However, if there happens to be a day when I have a lot of visitors, the plugin seems to remember the previous dingdongs and therefore when the fifth person for example is at the front door, I get to hear the jingle 5 times in a row.

Now I've seen in the logfiles that the plugin is doing a daily cleanup around 4-5am. Is there a command I could use to get this 'clean' done so that the plugin does not remember how many times the bell was used.

Thanks!

**Comment by Liver64** [comment]
No, the cleanup just delete physically the MP3 files. T me it looks like that the ding dong call does not end correctly so that the loaded file in the Sonos Queue has not been deleted by the Plugin. Please delete your Queue and check frequently the error log.
