### ISSUE TITLE
ENH: playmode case insensitive

### ISSUE THREAD

**Issue by Woersty** [Liver64/LoxBerry-Sonos#4]
Hallo,

schlage vor, den playmode caseinsensitive zu machen.

**Comment by Woersty** [comment]
Upps. Das ist ja noch die 1.0.1 hier.

**Comment by Liver64** [comment]
schau ich mir mal an, ändere prinzipiell seeeehr ungerne die Syntax weil man sich sonst komplett durch seine MS Konfiguration wühlen muss.

**Comment by Woersty** [comment]
Die Syntax ist mit der Änderung case-insensitive.
Bei dir war sie es nicht. 
Also löst siehe eher das Problem, dass man sich durch die MS Konfig wühlen muss.
Er nimmt den Parameter an wie er kommt und wandelt ihn fix in Grossschreibung für die PHP Klasse

**Comment by Liver64** [comment]
habe mal dein "preg_replace" rausgenommen, dann haben auch wieder alle playmodes in kleinschreibung funktioniert.

**Comment by Woersty** [comment]
Warum? Wovon redest du?
Das preg_replace ist schon ok an der Stelle.
Aber du musst den _ noch hinzufügen. Ich hatte die Kombimodes nicht beachtet.
Mit der Schreibweise hat das nix zu tun.
Also `preg_replace("/[^a-zA-Z0-9_]+/", "", strtoupper($_GET['playmode']));`

**Comment by Liver64** [comment]
jetzt passts :-)

**Comment by Liver64** [comment]
ok, funzt jetzt
