### ISSUE TITLE
Players not shown after configuration

### ISSUE THREAD

**Issue by heimpionier** [Liver64/Loxberry-Sonos#41]
I use the plugin version 5.2.6. When I scan for players, they are shown and I can configure them. But after saving the configuration and the message that everything worked fine, there are no players shown. The log file displays the message: "ERROR: system/ms_inbound.php: There are no Sonos Players already fully configured, please check/complete your Plugin Config and save your config before downloading your Template!".

In earlier attempts the log files displayed the message: "/bin/push_loxone.php: The configuration file could not be loaded, the file may be disrupted. We have to abort :-("

Can anybody help what is the problem?

**Comment by Liver64** [comment]
is this still the case?

**Comment by Liver64** [comment]
no answer
