### ISSUE TITLE
Cannot scan after upgrade to loxberry 3.0

### ISSUE THREAD

**Issue by sennevb** [Liver64/Loxberry-Sonos#42]
Hello,

Was using your plugin without problems, started a fresh install for loxberry 3.0.
When iscan for player i get following errors:
No valid data has been received after scanning for Players, we abort here.
Invalid do parameter:

**Comment by heubi76** [comment]
Same Problem here with an new install on a RPI4 with 3.0.0.1.

**Comment by Liver64** [comment]
Did the installation failed? Did you checked Install log? 
Maybe install again...

**Comment by heubi76** [comment]
All looks good, see log
[Sonos.log](https://github.com/Liver64/LoxBerry-Sonos/files/10907981/Sonos.log)

**Comment by Liver64** [comment]
I can not replicate because I just upgraded to v3.0.0.1.

**Comment by heubi76** [comment]
was also not working with 3.0.0, tried already with new install...any other diagnostic for the scan problem?

**Comment by Liver64** [comment]
what about detailed log post scan activity? Please select 1st debug level

**Comment by heubi76** [comment]
[sonos.log](https://github.com/Liver64/LoxBerry-Sonos/files/10908294/sonos.log)

**Comment by Liver64** [comment]
please execute in browser http://YOUR LB IP/plugins/sonos4lox/system/network.php and let me know what exactly appears onScreen. Please check also error log after execution. This is the detailed function been executed for scanning.

**Comment by heubi76** [comment]
looks like directly it's working? Last entry: 11:40:41.473 OK: system/network.php: JSON data has been successfully passed to application
Unfortunatelly with Scan Button not working?

**Comment by Liver64** [comment]
What exactly appears on the screen after execution? Was it totally empty or [ ] or...? What about log file after scanning?

**Comment by heubi76** [comment]
[php.log](https://github.com/Liver64/LoxBerry-Sonos/files/10908603/php.log)
![sonos](https://user-images.githubusercontent.com/25635057/223402995-6e1c9acd-cf83-4d74-b513-8ec3bcbc7e6e.jpg)
![sonos1](https://user-images.githubusercontent.com/25635057/223402998-fc3b6276-79ec-4e3d-ac2d-9ed5f1f6c877.jpg)

**Comment by heubi76** [comment]
[sonos.log](https://github.com/Liver64/LoxBerry-Sonos/files/10908619/sonos.log)

**Comment by Liver64** [comment]
excute http://your/ LB IP/plugins/sonos4lox/system/network.php in Browser, check screen output (empty, [ ], or list of Players? Then check error log in Sonos Plugin!
How does your *.cfg files looks like?

**Comment by heubi76** [comment]
Output of php:  See php.log
Found every player...looks ok

[message] => Notice (8): Undefined variable: value in [/opt/loxberry/webfrontend/html/plugins/sonos4lox/system/network.php, line 231]
)

**Comment by Liver64** [comment]
please open file webfrontend/html/plugins/sonos4lox/system/network.php using Notepad++ (NOT the PC Editor) scroll down to row 231 and change as below: 

IS: if(isSpeaker($model) == true and $value != $room) {
NEW: if(isSpeaker($model) == true) {

try again scanning

**Comment by heubi76** [comment]
unfortunatelly still same...multicast problem with my unifi network?
[sonos.log](https://github.com/Liver64/LoxBerry-Sonos/files/10909994/sonos.log)

**Comment by sennevb** [comment]
Same as heubi76:
Edited the line 231 aswell , still no scanning, when i run plugins/sonos4lox/system/network.php it shows the players, so it seems an error when it tries to parse the array

updated to loxberry version 3.0.1 but still same problem

edit: the error on line 231 seems a notice not an actual error

**Comment by Liver64** [comment]
Looks like a Loxberry issue. What type of hardware you are using?

**Comment by sennevb** [comment]
I'm using fresh dietPI install , then installed loxberry..
Running on synology Virtual machine.

Was running same setup for loxberry 2 and sonos4lox was running fine before

edit: Heubi76 running on RPI so might not be the hardware..

You cant replicate on your side?

**Comment by sennevb** [comment]
seems we are not the only one(s) who are getting this problem:
https://www.loxforum.com/forum/projektforen/loxberry/plugins/74862-loxberry-sonos-plugin-verf%C3%BCgbar/page90

**Comment by Liver64** [comment]
correct, the issue is only on fresh installed DietPi's with PHP-CLI. It is an Loxberry issue they are working on :-)

**Comment by sennevb** [comment]
So the fix is in a loxberry update and not with sonos plugin, correct?

Then we will wait patiently for a fix..

Thanks for looking into this

**Comment by Liver64** [comment]
you can fix it by using following code as root user:

rm /etc/php/7.4/cli/conf.d/20-loxberry-cli.ini

ln -s /opt/loxberry/system/php/loxberry-cli.ini /etc/php/7.4/cli/conf.d/20-loxberry-cli.ini

then it should work again.

**Comment by Liver64** [comment]
right, Not sure if they do an LB update immediately. You can fix it by those two lines of code.
