### ISSUE TITLE
Sonos Era not being detected

### ISSUE THREAD

**Issue by pforrmi** [Liver64/Loxberry-Sonos#43]
Hi,

maybe you already know, but the new Sonos speakers seems not to be detected.
I've got the Era 100 and it won't show up.

If I could assist with some data or something else please let me know.

Regards

**Comment by Liver64** [comment]
Please check error log after scanning procedure, there the model is listed which I need to know so that I can add the Era. Thx

**Comment by pforrmi** [comment]
In which logfile exactly I can find it?

**Comment by Liver64** [comment]
Sonos Log as always

**Comment by Liver64** [comment]
Sonos Log as always

**Comment by pforrmi** [comment]
Can't see any model listed there .... 

[sonos.log](https://github.com/Liver64/LoxBerry-Sonos/files/11208145/sonos.log)

**Comment by Liver64** [comment]
please try follwoing in your browser:
http://<IP-OF-ERA>:1400/xml/device_description.xml
and send me the result please

**Comment by pforrmi** [comment]
Attached.

[device_description.txt](https://github.com/Liver64/LoxBerry-Sonos/files/11230160/device_description.txt)

**Comment by pforrmi** [comment]
Attached.

[device_description.txt](https://github.com/Liver64/LoxBerry-Sonos/files/11230172/device_description.txt)

**Comment by Liver64** [comment]
[network.txt](https://github.com/Liver64/LoxBerry-Sonos/files/11230288/network.txt)

Please put file to webfrontend/html/plugins/sonos4lox/system and rename to "network.php", Then start your scan process again and let me know the result. Good luck

**Comment by pforrmi** [comment]
Hi and sorry for late reply...

If it use your file it just shows:

`
Ein Fehler ist aufgetreten :(...
Es wurden keine validen Daten vom Scannen nach Playern erhalten, wir brechen hier ab
`
