### ISSUE TITLE
Request: Support for PHP 8.2

### ISSUE THREAD

**Issue by Noschvie** [Liver64/Loxberry-Sonos#46]
Hello
please have a look to this [discussion](https://github.com/mschlenstedt/Loxberry/issues/1462) about LoxBerry for Bookworm.
But I don't know about details and effort, sorry...

**Comment by Bartel-C8** [comment]
I have some progress, with basic functionality working. But many other changes/tests will be needed.

Will commit my changes on a fork

**Comment by Letrab** [comment]
https://github.com/Letrab/LoxBerry-Sonos/tree/php8Fixes

Commit message explains the changes. Only tested discovery and "say" action

**Comment by Letrab** [comment]
https://github.com/Liver64/LoxBerry-Sonos/pull/48 

First changes

**Comment by Liver64** [comment]
closed
