### ISSUE TITLE
Elevenlabs API Key longer than expected by Sonos4Loxone

### ISSUE THREAD

**Issue by cruiseaddict** [Liver64/Loxberry-Sonos#59]
Today wanted to try T2S via Elevenlabs.
Pasted the 51 character API key from "profile + API key" at Elevenlabs, but Sonos4Loxnone expects a 32 character API key.

**Comment by Liver64** [comment]
But the key itself has just 32 digits!!

**Comment by unserbaublog** [comment]
Excellent. Have you got a hint how to fetch a key with 32 digits?
Mine looks like sk_xxxxxx423f22728d513e7ae06a5e27f18cb531705678yyyy and is definitely longer than 32 chars 🤣

**Comment by Liver64** [comment]
will be fixed with next Bugfix Release

**Comment by Liver64** [comment]
install v5.7.0

**Comment by unserbaublog** [comment]
Thank you. Much appreciated.
