### ISSUE TITLE
softstop cut off after 17 seconds

### ISSUE THREAD

**Issue by Woersty** [Liver64/LoxBerry-Sonos#6]
Softstop funktioniert nicht, wenn die Musik vorher relativ laut war.
Dein sleep 17 Sekunden reicht nicht. 
Bei mir braucht er von 100% auf 0 % etwa 80 Sekunden.

**Comment by Liver64** [comment]
17 Sekunden sind hardcoded in Sonos, steht nur als eine von 3 Möglichkeiten zur Verfügung.
Passe ggf. den Parameter Volume in der Plugin Config an, dann geht die Lautstärke schneller gen Null

**Comment by Woersty** [comment]
Wenn ich 90 Sekunden eintrage, funktioniert es aber schön soft.
Und das Sleep hast du bei dir drin. Sehe nicht, wo das was mit Sonos zu tun hätte:
https://github.com/Liver64/LoxBerry-Sonos/blob/master/webfrontend/html/sonos2.php#L395

**Comment by Liver64** [comment]
Das sleep 17 ist nur drin weil er max. warten soll um dann wieder die Lautstärke auf vorherigen Wert zu stellen. Der Parameter ramptovolume "SLEEP_TIMER_RAMP_TYPE" enthält die 17 Sekunden (siehe SonosPHP)

**Comment by Woersty** [comment]
Ja, aber mit dem Befehl killst du das Ausblenden.
Probiere es doch mal aus. 😄

**Comment by Liver64** [comment]
habs umgebaut:
`
while ($sonos->GetVolume() > 0) {

sleep('1');
}
$sonos->Pause();`

**Comment by Woersty** [comment]
So ist es noch besser. 👍

**Comment by Woersty** [comment]
Nachtrag: Vielleicht solltest du noch einen max-Loop-Counter einbauen.
Falls man während des Ausblendens zwischenfunkt, läuft die Schleife sonst weiter und weiter...
